name: Jandex Release

on:
  pull_request:
    types:
    - closed
    paths:
    - '.github/project.yml'

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    if: ${{github.event.pull_request.merged == true}}
    env:
      GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
    steps:
    - name: Retrieve project metadata
      id: metadata
      uses: radcortez/project-metadata-action@master
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        metadata-file-path: '.github/project.yml'

    - name: Checkout
      uses: actions/checkout@v3
      with:
        token: ${{secrets.RELEASE_TOKEN}}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: 17

    - name: Maven release ${{steps.metadata.outputs.current-version}}
      run: |
        java -version
        gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" --output smallrye-sign.asc .github/release/smallrye-sign.asc.gpg
        gpg --quiet --batch --yes --decrypt --passphrase="${{secrets.SECRET_PASSPHRASE}}" --output maven-settings.xml .github/release/maven-settings.xml.gpg
        gpg --fast-import --no-tty --batch --yes smallrye-sign.asc
        git config --global user.name "SmallRye CI"
        git config --global user.email "smallrye@googlegroups.com"
        git checkout -b release
        sed -i -e 's|<version.jandex>.*</version.jandex>|<version.jandex>${{steps.metadata.outputs.current-version}}</version.jandex>|' benchmarks/pom.xml
        sed -i -e 's|^version: main|version: ${{steps.metadata.outputs.current-version}}|' doc/antora.yml
        git commit -a -m 'Amendments before release'
        mvn -B release:prepare -Prelease -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}} -s maven-settings.xml
        git checkout ${{github.base_ref}}
        git rebase release
        mvn -B release:perform -Prelease -s maven-settings.xml
        sed -i -e 's|<version.jandex>.*</version.jandex>|<version.jandex>${project.version}</version.jandex>|' benchmarks/pom.xml
        sed -i -e 's|^version: ${{steps.metadata.outputs.current-version}}|version: main|' doc/antora.yml
        git commit -a -m 'Amendments after release'
        git push
        git push --tags

    - uses: radcortez/milestone-release-action@master
      name: Milestone release
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        milestone-title: ${{steps.metadata.outputs.current-version}}

  github-pages:
    name: GitHub Pages
    needs:
    - release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: Set up Node.js 16
      uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Generate and push
      run: |
        node --version
        
        curl -s -L -o antora-playbook.yml https://github.com/smallrye/jandex/blob/main/doc/antora-playbook-prod.yml?raw=true

        npm install @antora/cli@3.0 @antora/site-generator-default@3.0
        npx antora generate antora-playbook.yml
        
        rm -rf node_modules docs package.json package-lock.json antora-playbook.yml
        mv -T build/site docs
        touch docs/.nojekyll

        git config --global user.name "SmallRye CI"
        git config --global user.email "smallrye@googlegroups.com"
        git status
        git add -A .
        git commit -m 'Generate documentation site'
        git push
